alipay:
  # 沙箱应用 APPID
  app_id: "9021000166657443"

  # 你的应用私钥，PKCS8 格式
  private_key: |
    MIIEpAIBAAKCAQEAnuu3hGSnbdebQpCMA1RIVc1meNhhezD4IzGde8+mxqo4sgqICSrFe938WyDnaOjxELFODUJbZ7Yw1uHL5WXizUICmf2QlrHAgoWxshknPYVfhI/jcoOCYJkr8MnpgPmnCCgOyPr0K7zb7/jo6GWU3KAMCZPvmWidSgvvAIs6f45/1PtauWdflv4sNm5r/0ZzWwvTC1Nj4W0vWaPBeyIJpoaFaTEdHUecvEXOV5QQSduk7kT0g0ZVBrWldG10JuL5nIlWSKmjQ9T9UxeTOlEG5br4vyEnBU8m/Lob0w6bQUifTwHZqFPASaieJ3JwoLCXyGLdmSXknQCdshsnhxsk3QIDAQABAoIBAQCBV4GOTEmEebVQkMqTrxYMV1buRdXY6LscEbaF3TR0fngUV8PuChSewsYv+PC+jtAccOIAoqA4Ia1QRoenVawouG/bmucB7vuqf1tng1dPl+xsvJs2SVhkfGWp3Puh0A6k8c1OwAjYTCaJAgG1m29zvQLvDKs2JVHWwS2tOKPMygcz8uPcTMGuk3hUXeSQzsGhJIz3pWy9/LFZuIwF5l6COmIAiZ4vR5+Rs6Ax3AjK4tp3fFN6FHv9TqYRYQs1hq+a2xDVL1kXbShGS2vaSZ632CyjEfBQMmQuAgR0gDoQMDqYAi81+GAepvMboZvNM3gc3lvsstGj+4EyHrmpC/SVAoGBAOflCiFW8lKRrefh6TpYSUQeI+c0Aro3vTMesLHaxufNQUvG+qvf/MhA71Ud9Sy7gx1DvpVKDHNoX7KD+kHhVYS673U9uK7qNq5smClyMeqj5K9sTh+ud4AQE04vhsMOreC8C0PZfBVWHOoPiDuFdxgsoPetMdCvGvwVpHP6SbEzAoGBAK9ww9OibnTZ8JgmNEKurR4JeoG6a5dAAWDSH9FInpKcIBwMyr489kmnrK62i6UE4WodMMS4oPWqvoEK3G1bAIJiaVCE8Ef/JZVQ+wwgOTb7ugPecsXm/xof6frBnYkXKhUOEQAimHVDnYLAeqfWzUEKaErqxiPq1spYpHhpbvGvAoGBAKUAa/zdCP+HeN6N+I3zU+6MI6/Xajlmf9Fn/QIQUYeOnO92Xdb+QbebvLAr6NAzfE/ObEV9su5LTgyPq/pEg7015jzd9hM/xDjIPF0BTFNQ2t+XiN8yHQWaaqIvXwxb3Y0TQFC+53OnGlvRQXZYuS0SVFbnfZKnhePo4mNDrDvRAoGAdIwT+3bvq/7QPzM6CoZiCQ9A7Ad8zBjAEaLlcjGs7jZ7ekbhNOnor1uNcu9f63tHiCfmKvmALFOGhNFDR/5pYzSfQ9dcjGeqfvwyGocZmzY1B7byRhhDpgZHeMbAsb7KvPwAPTe+UkBd1euqT+95oViZmhNHF7s9f2TNthRMmI8CgYAc1U7Pjg+hztS3W8OJJfA2pd8ZsCmi2mX2xh3WzEwLN8LOtEIKH2EX7Z+tXgz1BrpCI/wVmbmfYMp2Ef+AxOVyGQqMjfZo1F9Bhk6DCfLy5i0ucL28KQzScO92mvIzUsu0bsYjXA2BRm4vImvx7X/u2A8F9XR+OgGXwIOR3J8Ycw==

  # 支付宝公钥，不是应用公钥
  alipay_public_key: |
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5MUGVP9pqZLBEOFYaXu94k/4KgRHMAkDfo6Lvui8G9a2EeKPKzBjrnkgkmIsgSqWXxG+KO3A2xMKFRcHUQcgvKgJWyWwxJv3L6XPGNuWJlHo7G1ua3NvEe9Npfz5xBWY5nnpJEqLYVIPlDkqNUMd3yRGiET1EkFOBoYV0H+N7dYBjNPrDv2rWajADtLGGnxveEIIU7Gb+6oghmya1QDJu2AKqJvg+fz7rujuMlGyOQ2oT7MPD7lqymFtHmqonG+i4HHLDMa/lft1ryIkN4HGwr7zASSpetBPWrHS42grOgxgdluDBBhVKuix2rhQ+cm42A6SDEY7sb0+80AVN8I9wIDAQAB

  # 当前新版沙箱网关
  gateway_url: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"


  # 支付结果异步通知地址
  notify_url: "http://8.138.57.34:1077/pay/notify"

  charset: "UTF-8"
  sign_type: "RSA2"
  format: "JSON"
