database:
  mysql:
    host: "127.0.0.1"
    db-name: "shop"
    user: "root"
    pass: "Aa123098.."
    port: 3306
  postgresql:
    host: "127.0.0.1"
    db-name: "shop"
    user: "root"
    pass: "Aa123098.."
    port: 9920