package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
)

func main() {
	in := flag.String("in", "config.txt", "业务配置文件")
	out := flag.String("out", "zz_generated_config.go", "生成后的 Go 文件")
	pkg := flag.String("pkg", "test_t", "生成文件所属包名")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		exit(fmt.Errorf("读取配置失败: %w", err))
	}

	appName := strings.TrimSpace(string(raw))
	if appName == "" {
		exit(fmt.Errorf("配置不能为空"))
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("// 该文件由 config.txt 生成，用于演示源码层生成代码。\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *pkg)
	fmt.Fprintf(&buf, "// GeneratedAppName 是由 go:generate 生成的业务配置。\n")
	fmt.Fprintf(&buf, "const GeneratedAppName = %q\n", appName)

	content, err := format.Source(buf.Bytes())
	if err != nil {
		exit(fmt.Errorf("格式化生成代码失败: %w", err))
	}
	if err := os.WriteFile(*out, content, 0o644); err != nil {
		exit(fmt.Errorf("写入生成文件失败: %w", err))
	}
}

func exit(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
