gin:
  port: ":3100"
  # 读取请求的最大持续时间
  read-timeout: 10
  # 写入响应的最大持续时间
  write-timeout: 10
  # 请求头的最大字节数
  max-header-bytes: 1048576

gorm:
  # 全字段查询
  query-fields: true
  # 是否关闭单表复数s
  singular-table: true
  # 使用的数据库
  use-database: "mysql"
  # 支持的数据库
  database:
    # mysql 数据库配置
    mysql:
      # 服务地址
      host: "127.0.0.1"
      # 数据库名
      db-name: "exchange"
      # 用户名
      user: "root"
      # 密码
      pass: "Aa123098.."
      # 端口
      port: 3306
      # postgresql 数据库配置

    postgresql:
      # 服务地址
      host: "127.0.0.1"
      # 数据库名
      db-name: "shop"
      # 用户名
      user: "root"
      # 密码
      pass: "Aa123098.."
      # 端口
      port: 9920
  gen:
    # 指定生成代码的路径
    out-path: "/Users/taozi/Documents/Golang/gotest/gen/query"
    # 指定模式
    mode:
      - "WithoutContext"
      - "WithDefaultQuery"
      - "WithQueryInterface"
# Redis配置
redis:
  # 开启订阅
  use-pub: true
  # 连接池连接
  pool:
    # 连接协议
    network: "tcp"
    # 服务器地址
    server: "127.0.0.1"
    # 端口
    port: 6379
    # 密码
    pass: ""
    # 数据库 0-15
    dbname: 0
    # 连接超时时间
    connect-timeout: 30
    # 读取超时时间
    read-timeout: 30
    # 写入超时时间
    Write-timeout: 30
    # 设置最大连接数
    max-open-conn: 0
    # 空闲连接超时
    conn-max-idle-time: 30
    # 最大空闲连接数
    max-idle-conn: 0
    # 如果超过最大连接数是否等待
    wait: false

elasticsearch:
  # ip地址
  ip-address:
  - "http://47.101.70.217:1014"
  # 每个主机的最大空闲连接数
  max-idle-conns-per-host: 10
  # 接收响应头的超时时间
  response-header-timeout: 5
  # 建立连接的上下文和超时设置
  dialer-timeout: 5

logs:
  use-log: "zap"
  instance:
    zap:
      # 默认开发模式： devel ，自定义模式 custom，生产模式 product，
      mode: "custom"
      # 日志级别： debug,info,warn,error,dpanic,panic,fatal,
      level: "info"
      # 输出格式： json，控制台 console
      encoding: "console"
      # 时间格式，
      # 长日期格式 long: [2006-01-02 15:04:05.000]
      # 短日期格式 short: [15:04:05.000]
      # iso8601: 2006-01-02T15:04:05Z0700
      # rfc3339: 2006-01-02T15:04:05Z07:00
      # rfc3339nano：2024-01-30T15:04:05.999999999-08:00
      format-time: "short"
      # 文件路径类型 full 绝对路径 ，short 相对路径
      file-length: "full"
      # 日志输出位置：stderr 控制台, ./common/file/logs/app.log 项目日志文件路径
      out-path:
        - "stderr"
        - "/home/programmer-yan/Documents/GoFile/gotest/common/file/logs/app.log"
      err-out-path:
        - "/home/programmer-yan/Documents/GoFile/gotest/common/file/logs/zap_err.log"
