gin:
  port: ":3100"
  # 读取请求的最大持续时间
  read-timeout: 10
  # 写入响应的最大持续时间
  write-timeout: 10
  # 请求头的最大字节数
  max-header-bytes: 1048576
database:
  # 使用的数据库
  use-database: "mysql"
  # mysql 数据库配置
  mysql:
    # 服务地址
    host: "127.0.0.1"
    # 数据库名
    db-name: "shop"
    # 用户名
    user: "root"
    # 密码
    pass: "Aa123098.."
    # 端口
    port: 3306
    # postgresql 数据库配置
  postgresql:
    # 服务地址
    host: "127.0.0.1"
    # 数据库名
    db-name: "shop"
    # 用户名
    user: "root"
    # 密码
    pass: "Aa123098.."
    # 端口
    port: 9920

# Redis配置
redis:
  # 连接协议
  network: "tcp"
  # 服务器地址
  server: "127.0.0.1"
  # 端口
  port: 6379
  # 密码
  pass: ""
  # 数据库 0-15
  dbname: 0
  # 连接超时时间
  connect-timeout: 30
  # 读取超时时间
  read-timeout: 30
  # 写入超时时间
  Write-timeout: 30
  # 设置最大连接数
  max-open-conn: 0
  # 空闲连接超时
  conn-max-idle-time: 30
  # 最大空闲连接数
  max-idle-conn: 0
  # 如果超过最大连接数是否等待
  wait: false